### ISSUE TITLE
LookupError: unknown encoding:

### ISSUE THREAD

**Issue by Mparaiso** [setumiami/sublime-typescript-compiler#6]
Hi , using this plugin with ST2 on Windows 8.1 I get the following error each time I try to compile a ts file : 

```
Exception in thread Thread-39:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\typescript_compiler.py", line 175, in run
  File ".\typescript_compiler.py", line 131, in _make_text_safeish
LookupError: unknown encoding: 
```

**Comment by drivo** [comment]
I guess Windows 8.1 is not able to detect 'utf-8' as a valid encoding label. I added in the v0.1.2 a fallback for encoding issues. Let me know if this last fix would fix your case.

**Comment by Mparaiso** [comment]
ok,i'll try that asap. thanks.

2015-06-02 16:13 GMT+02:00 setumiami notifications@github.com:
